
// This file has been generated by the GUI designer. Do not modify.
namespace Tacto.Gui
{
	public partial class DlgEditPerson
	{
		private global::Gtk.Notebook nbFiles;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Entry edName;
		
		private global::Gtk.HBox hbox11;
		
		private global::Gtk.Label label11;
		
		private global::Gtk.Entry edSurname;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Entry edEmail;
		
		private global::Gtk.Button btConnectEmail;
		
		private global::Gtk.HBox hbox8;
		
		private global::Gtk.Label label8;
		
		private global::Gtk.Entry edMPhone;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label label6;
		
		private global::Gtk.Label lblCategories;
		
		private global::Gtk.Expander expCategories;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.ComboBox cbAvailableCategories;
		
		private global::Gtk.Button btAddCategory;
		
		private global::Gtk.HBox hbox7;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.ComboBox cbCurrentCategories;
		
		private global::Gtk.Button btRemoveCategory;
		
		private global::Gtk.Label GtkLabel4;
		
		private global::Gtk.Expander expSaveAs;
		
		private global::Gtk.HBox hbox12;
		
		private global::Gtk.ComboBox cbOutputFormat;
		
		private global::Gtk.Button btSaveAs;
		
		private global::Gtk.Label GtkLabel7;
		
		private global::Gtk.Label label12;
		
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox9;
		
		private global::Gtk.Label label9;
		
		private global::Gtk.Entry edEmail2;
		
		private global::Gtk.Button btConnectEmail2;
		
		private global::Gtk.HBox hbox15;
		
		private global::Gtk.Label label16;
		
		private global::Gtk.Entry edWeb;
		
		private global::Gtk.Button btConnectWeb;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry edWPhone;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label label7;
		
		private global::Gtk.Entry edHPhone;
		
		private global::Gtk.HBox hbox10;
		
		private global::Gtk.Label label10;
		
		private global::Gtk.Entry edAddress;
		
		private global::Gtk.HBox hbox13;
		
		private global::Gtk.Label label14;
		
		private global::Gtk.Entry edId;
		
		private global::Gtk.HBox hbox14;
		
		private global::Gtk.Label label15;
		
		private global::Gtk.Entry edComments;
		
		private global::Gtk.Label label13;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Tacto.Gui.DlgEditPerson
			this.Name = "Tacto.Gui.DlgEditPerson";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Tacto.Gui.DlgEditPerson.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.nbFiles = new global::Gtk.Notebook ();
			this.nbFiles.CanFocus = true;
			this.nbFiles.Name = "nbFiles";
			this.nbFiles.CurrentPage = 0;
			// Container child nbFiles.Gtk.Notebook+NotebookChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = "<b>Name</b>";
			this.label1.UseMarkup = true;
			this.hbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.edName = new global::Gtk.Entry ();
			this.edName.CanFocus = true;
			this.edName.Name = "edName";
			this.edName.IsEditable = true;
			this.edName.InvisibleChar = '●';
			this.hbox2.Add (this.edName);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.edName]));
			w3.Position = 1;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = "<b>Surname</b> <i>(or activity)</i>";
			this.label11.UseMarkup = true;
			this.hbox11.Add (this.label11);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.label11]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.edSurname = new global::Gtk.Entry ();
			this.edSurname.CanFocus = true;
			this.edSurname.Name = "edSurname";
			this.edSurname.IsEditable = true;
			this.edSurname.InvisibleChar = '●';
			this.hbox11.Add (this.edSurname);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.edSurname]));
			w6.Position = 1;
			this.vbox3.Add (this.hbox11);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox11]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = "<b>Email</b>";
			this.label2.UseMarkup = true;
			this.hbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.label2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.edEmail = new global::Gtk.Entry ();
			this.edEmail.CanFocus = true;
			this.edEmail.Name = "edEmail";
			this.edEmail.IsEditable = true;
			this.edEmail.InvisibleChar = '●';
			this.hbox3.Add (this.edEmail);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.edEmail]));
			w9.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btConnectEmail = new global::Gtk.Button ();
			this.btConnectEmail.CanFocus = true;
			this.btConnectEmail.Name = "btConnectEmail";
			this.btConnectEmail.UseStock = true;
			this.btConnectEmail.UseUnderline = true;
			this.btConnectEmail.Label = "gtk-connect";
			this.hbox3.Add (this.btConnectEmail);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btConnectEmail]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = "<b>Mobile phone</b>";
			this.label8.UseMarkup = true;
			this.hbox8.Add (this.label8);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.label8]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.edMPhone = new global::Gtk.Entry ();
			this.edMPhone.CanFocus = true;
			this.edMPhone.Name = "edMPhone";
			this.edMPhone.IsEditable = true;
			this.edMPhone.InvisibleChar = '●';
			this.hbox8.Add (this.edMPhone);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.edMPhone]));
			w13.Position = 1;
			this.vbox3.Add (this.hbox8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = "Current categories:";
			this.hbox6.Add (this.label6);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label6]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.lblCategories = new global::Gtk.Label ();
			this.lblCategories.Name = "lblCategories";
			this.lblCategories.LabelProp = "All";
			this.hbox6.Add (this.lblCategories);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.lblCategories]));
			w16.Position = 1;
			this.vbox3.Add (this.hbox6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox6]));
			w17.Position = 4;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expCategories = new global::Gtk.Expander (null);
			this.expCategories.CanFocus = true;
			this.expCategories.Name = "expCategories";
			// Container child expCategories.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = "Add category:";
			this.hbox5.Add (this.label5);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label5]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.cbAvailableCategories = global::Gtk.ComboBox.NewText ();
			this.cbAvailableCategories.Name = "cbAvailableCategories";
			this.hbox5.Add (this.cbAvailableCategories);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.cbAvailableCategories]));
			w19.Position = 1;
			// Container child hbox5.Gtk.Box+BoxChild
			this.btAddCategory = new global::Gtk.Button ();
			this.btAddCategory.CanFocus = true;
			this.btAddCategory.Name = "btAddCategory";
			this.btAddCategory.UseStock = true;
			this.btAddCategory.UseUnderline = true;
			this.btAddCategory.Label = "gtk-add";
			this.hbox5.Add (this.btAddCategory);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.btAddCategory]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox5]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = "Remove category:";
			this.hbox7.Add (this.label4);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.label4]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.cbCurrentCategories = global::Gtk.ComboBox.NewText ();
			this.cbCurrentCategories.Name = "cbCurrentCategories";
			this.hbox7.Add (this.cbCurrentCategories);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.cbCurrentCategories]));
			w23.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.btRemoveCategory = new global::Gtk.Button ();
			this.btRemoveCategory.CanFocus = true;
			this.btRemoveCategory.Name = "btRemoveCategory";
			this.btRemoveCategory.UseStock = true;
			this.btRemoveCategory.UseUnderline = true;
			this.btRemoveCategory.Label = "gtk-remove";
			this.hbox7.Add (this.btRemoveCategory);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.btRemoveCategory]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox2.Add (this.hbox7);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.expCategories.Add (this.vbox2);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = "Manage categories";
			this.GtkLabel4.UseUnderline = true;
			this.expCategories.LabelWidget = this.GtkLabel4;
			this.vbox3.Add (this.expCategories);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.expCategories]));
			w27.Position = 5;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.expSaveAs = new global::Gtk.Expander (null);
			this.expSaveAs.CanFocus = true;
			this.expSaveAs.Name = "expSaveAs";
			this.expSaveAs.Expanded = true;
			// Container child expSaveAs.Gtk.Container+ContainerChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.cbOutputFormat = global::Gtk.ComboBox.NewText ();
			this.cbOutputFormat.AppendText ("HTML");
			this.cbOutputFormat.AppendText ("CSV");
			this.cbOutputFormat.AppendText ("VCard");
			this.cbOutputFormat.Name = "cbOutputFormat";
			this.hbox12.Add (this.cbOutputFormat);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.cbOutputFormat]));
			w28.Position = 0;
			// Container child hbox12.Gtk.Box+BoxChild
			this.btSaveAs = new global::Gtk.Button ();
			this.btSaveAs.CanFocus = true;
			this.btSaveAs.Name = "btSaveAs";
			this.btSaveAs.UseStock = true;
			this.btSaveAs.UseUnderline = true;
			this.btSaveAs.Label = "gtk-save-as";
			this.hbox12.Add (this.btSaveAs);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.btSaveAs]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.expSaveAs.Add (this.hbox12);
			this.GtkLabel7 = new global::Gtk.Label ();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = "Save as...";
			this.GtkLabel7.UseUnderline = true;
			this.expSaveAs.LabelWidget = this.GtkLabel7;
			this.vbox3.Add (this.expSaveAs);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.expSaveAs]));
			w31.Position = 6;
			w31.Expand = false;
			w31.Fill = false;
			this.nbFiles.Add (this.vbox3);
			// Notebook tab
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.LabelProp = "Basic";
			this.nbFiles.SetTabLabel (this.vbox3, this.label12);
			this.label12.ShowAll ();
			// Container child nbFiles.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = "Email(2)";
			this.hbox9.Add (this.label9);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.label9]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.edEmail2 = new global::Gtk.Entry ();
			this.edEmail2.CanFocus = true;
			this.edEmail2.Name = "edEmail2";
			this.edEmail2.IsEditable = true;
			this.edEmail2.InvisibleChar = '●';
			this.hbox9.Add (this.edEmail2);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.edEmail2]));
			w34.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.btConnectEmail2 = new global::Gtk.Button ();
			this.btConnectEmail2.CanFocus = true;
			this.btConnectEmail2.Name = "btConnectEmail2";
			this.btConnectEmail2.UseStock = true;
			this.btConnectEmail2.UseUnderline = true;
			this.btConnectEmail2.Label = "gtk-connect";
			this.hbox9.Add (this.btConnectEmail2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.btConnectEmail2]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox4.Add (this.hbox9);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox9]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox15 = new global::Gtk.HBox ();
			this.hbox15.Name = "hbox15";
			this.hbox15.Spacing = 6;
			// Container child hbox15.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.LabelProp = "Web";
			this.hbox15.Add (this.label16);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.label16]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child hbox15.Gtk.Box+BoxChild
			this.edWeb = new global::Gtk.Entry ();
			this.edWeb.CanFocus = true;
			this.edWeb.Name = "edWeb";
			this.edWeb.IsEditable = true;
			this.edWeb.InvisibleChar = '●';
			this.hbox15.Add (this.edWeb);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.edWeb]));
			w38.Position = 1;
			// Container child hbox15.Gtk.Box+BoxChild
			this.btConnectWeb = new global::Gtk.Button ();
			this.btConnectWeb.CanFocus = true;
			this.btConnectWeb.Name = "btConnectWeb";
			this.btConnectWeb.UseStock = true;
			this.btConnectWeb.UseUnderline = true;
			this.btConnectWeb.Label = "gtk-connect";
			this.hbox15.Add (this.btConnectWeb);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox15 [this.btConnectWeb]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox4.Add (this.hbox15);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox15]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = "Work Phone";
			this.hbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label3]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.edWPhone = new global::Gtk.Entry ();
			this.edWPhone.CanFocus = true;
			this.edWPhone.Name = "edWPhone";
			this.edWPhone.IsEditable = true;
			this.edWPhone.InvisibleChar = '●';
			this.hbox4.Add (this.edWPhone);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.edWPhone]));
			w42.Position = 1;
			this.vbox4.Add (this.hbox4);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox4]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = "Home Phone";
			this.hbox1.Add (this.label7);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label7]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.edHPhone = new global::Gtk.Entry ();
			this.edHPhone.CanFocus = true;
			this.edHPhone.Name = "edHPhone";
			this.edHPhone.IsEditable = true;
			this.edHPhone.InvisibleChar = '●';
			this.hbox1.Add (this.edHPhone);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.edHPhone]));
			w45.Position = 1;
			this.vbox4.Add (this.hbox1);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
			w46.Position = 3;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = "Address";
			this.hbox10.Add (this.label10);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.label10]));
			w47.Position = 0;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.edAddress = new global::Gtk.Entry ();
			this.edAddress.CanFocus = true;
			this.edAddress.Name = "edAddress";
			this.edAddress.IsEditable = true;
			this.edAddress.InvisibleChar = '●';
			this.hbox10.Add (this.edAddress);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.edAddress]));
			w48.Position = 1;
			this.vbox4.Add (this.hbox10);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox10]));
			w49.Position = 4;
			w49.Expand = false;
			w49.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox ();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.LabelProp = "Id";
			this.hbox13.Add (this.label14);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.label14]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.edId = new global::Gtk.Entry ();
			this.edId.CanFocus = true;
			this.edId.Name = "edId";
			this.edId.IsEditable = true;
			this.edId.InvisibleChar = '●';
			this.hbox13.Add (this.edId);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox13 [this.edId]));
			w51.Position = 1;
			this.vbox4.Add (this.hbox13);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox13]));
			w52.Position = 5;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox ();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.LabelProp = "Comments";
			this.label15.Wrap = true;
			this.hbox14.Add (this.label15);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.label15]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.edComments = new global::Gtk.Entry ();
			this.edComments.CanFocus = true;
			this.edComments.Name = "edComments";
			this.edComments.IsEditable = true;
			this.edComments.InvisibleChar = '●';
			this.hbox14.Add (this.edComments);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox14 [this.edComments]));
			w54.Position = 1;
			this.vbox4.Add (this.hbox14);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox14]));
			w55.Position = 6;
			w55.Expand = false;
			w55.Fill = false;
			this.nbFiles.Add (this.vbox4);
			global::Gtk.Notebook.NotebookChild w56 = ((global::Gtk.Notebook.NotebookChild)(this.nbFiles [this.vbox4]));
			w56.Position = 1;
			// Notebook tab
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = "More..";
			this.nbFiles.SetTabLabel (this.vbox4, this.label13);
			this.label13.ShowAll ();
			w1.Add (this.nbFiles);
			global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(w1 [this.nbFiles]));
			w57.Position = 0;
			// Internal child Tacto.Gui.DlgEditPerson.ActionArea
			global::Gtk.HButtonBox w58 = this.ActionArea;
			w58.Name = "dialog1_ActionArea";
			w58.Spacing = 10;
			w58.BorderWidth = ((uint)(5));
			w58.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w59 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w58 [this.buttonCancel]));
			w59.Expand = false;
			w59.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w60 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w58 [this.buttonOk]));
			w60.Position = 1;
			w60.Expand = false;
			w60.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 420;
			this.DefaultHeight = 339;
			this.Show ();
			this.btConnectEmail.Clicked += new global::System.EventHandler (this.OnConnect);
			this.btAddCategory.Clicked += new global::System.EventHandler (this.OnAddCategory);
			this.btRemoveCategory.Clicked += new global::System.EventHandler (this.OnRemoveCategory);
			this.btSaveAs.Clicked += new global::System.EventHandler (this.OnSaveAs);
			this.btConnectEmail2.Clicked += new global::System.EventHandler (this.OnConnect);
			this.btConnectWeb.Clicked += new global::System.EventHandler (this.OnConnectWeb);
		}
	}
}
